### ISSUE TITLE
Need update [ E26 ] Insufficient memory requested. User provided `memory` is 2900 MB, but based on the EIF file size, the minimum memory should be 3016 MB

### ISSUE THREAD

**Issue by oday0311** [hxhwing/Nitro-Enclave-Demo#1] opened 2022-10-27 02:12 UTC
[ E26 ] Insufficient memory requested. User provided `memory` is 2900 MB, but based on the EIF file size, the minimum memory should be 3016 MB

**Comment by hxhwing** [comment] 2022-11-15 13:44
This is caused by size increase of base image Amazon Linux, fixed by [a2345df](https://github.com/hxhwing/Nitro-Enclave-Demo/commit/a2345df02b389792621de42100c911b7f0d41519)

**Closed as completed by hxhwing** 2022-11-15 13:44 UTC
